### ISSUE TITLE
Enable scanning all other supported files for trivy

### ISSUE THREAD

**Issue by pravindahal** [coopnorge/engineering-docker-images#2085]
For now, we are limiting trivy to scan only the terraform files. See here: https://github.com/coopnorge/engineering-docker-images/pull/2080

It would make sense to enable all other supported file types, but before that we need to resolve the following to make sure we comply or ignore the issues:
```[tasklist]
### Tasks
- [ ] AVD-DS-0026: Add HEALTHCHECK instruction in your Dockerfile
- [ ] AVD-DS-0002: Specify at least 1 USER command in Dockerfile with non-root user as argument
- [ ] AVD-DS-0013: MEDIUM: RUN should not be used to change directory (Dockerfile)
- [ ] AVD-DS-0029: ‘apt-get’ missing ‘–no-install-recommends’
```

The above are some of the common issues. There are many more in various repos.

**Comment by pravindahal** [comment]
We have hadolint and kubeconform for other things.
